FROM node:20-alpine as builder

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY . .

RUN npm run build

FROM node:20-alpine as production
WORKDIR /app

COPY --from=builder /app/package*.json ./

RUN npm i --omit=dev

COPY --from=builder /app/dist ./dist/

COPY --from=builder /app/public ./public

EXPOSE 3000

CMD ["node", "dist/main.js"]